stages:
  - "test"
  - "deploy"

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

eslint:
  image: node:latest
  stage: test
  except:
    - tags
  retry: 2
  script:
    - npm install @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint
    - npm run test:lint

sast:
  stage: test
  retry: 2
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

test:
  image: node:latest
  stage: test
  retry: 2
  allow_failure: true
  script:
    - npm install
    - TEST=1 npx nyc --reporter cobertura npm test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml


docker-publish:
  image: docker:latest
  stage: deploy
  only:
    - main
    - tags
  retry: 2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_PATH${tag}" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_PATH${tag}"
