version: "3.9"
services:
  cestmaddy:
    build: .
    command: bash -c "bash /cestmaddy/entrypoint.sh ${THEME} ${THEME_REPO} && npm start"
    ports:
      - "${PORT}:80"
    volumes:
      - ./config.yml:/cestmaddy/config.yml.original
      - ./source/:/cestmaddy/source