version: "3.9"
services:
  cestmaddy:
    image: "cestoliv/cestmaddy:latest"
    ports:
      - "${PORT}:80"
    volumes:
      - ./config.yml:/cestmaddy/config.yml
      - ./source/:/cestmaddy/source